server:
  servlet:
    context-path: /auth
  port: 63070
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/xuecheng_users?serverTimezone=UTC&userUnicode=true&useSSL=false&
    username: root
    password: password
weixin:
  appid: wxed9954c01bb89b47
  secret: a7482517235173ddb4083788de60b90e